openapi: 3.2.0
info:
  title: Avalara AvaTax Registrar API
  description: Welcome to the AvaTax API Postman Collection!
  version: 1.0.0
servers:
- url: http://{{baseurl}}
security:
- basicAuth: []
tags:
- name: Registrar
paths:
  /api/v2/accounts/{id}:
    delete:
      tags:
      - Registrar
      summary: Avalara DeleteAccount
      description: '# For Registrar Use Only

        This API is for use by Avalara Registrar administrative users only.


        Delete an account.

        Deleting an account will delete all companies, all account level users and license keys attached to this account.


        ### Security Policies


        * This API requires the user role SystemAdmin.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2AccountsById
      x-operation-id-source: derived
    put:
      tags:
      - Registrar
      summary: Avalara UpdateAccount
      description: '# For Registrar Use Only

        This API is for use by Avalara Registrar administrative users only.


        Replace an existing account object with an updated account object.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 12345
                name: Test Account
                effectiveDate: '2023-08-13T00:00:00+00:00'
                accountStatusId: Test
                accountTypeId: Regular
                isSamlEnabled: false
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiV2AccountsById
      x-operation-id-source: derived
  /api/v2/accounts:
    post:
      tags:
      - Registrar
      summary: Avalara CreateAccount
      description: '# For Registrar Use Only

        This API is for use by Avalara Registrar administrative users only.


        Create a single new account object.

        When creating an account object you may attach subscriptions and users as part of the ''Create'' call.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 12345
                name: Test Account
                effectiveDate: '2023-08-13T00:00:00+00:00'
                accountStatusId: Test
                accountTypeId: Regular
                isSamlEnabled: false
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2Accounts
      x-operation-id-source: derived
  /api/v2/notifications/{id}:
    delete:
      tags:
      - Registrar
      summary: Avalara DeleteNotification
      description: 'This API is available by invitation only.


        Delete the existing notification identified by this URL.


        A notification is a message from Avalara that may have relevance to your business. You may want

        to regularly review notifications and then dismiss them when you are certain that you have addressed

        any relevant concerns raised by this notification.


        An example of a notification would be a message about new software, or a change to AvaTax that may

        affect you, or a potential issue with your company''s tax profile.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

        * This API is available by invitation only. To request access to this feature, please speak to a business development manager and request access to [NotificationsAPI:Create].'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2NotificationsById
      x-operation-id-source: derived
    put:
      tags:
      - Registrar
      summary: Avalara UpdateNotification
      description: 'This API is available by invitation only.


        Replaces the notification identified by this URL with a new notification.


        A notification is a message from Avalara that may have relevance to your business. You may want

        to regularly review notifications and then dismiss them when you are certain that you have addressed

        any relevant concerns raised by this notification.


        An example of a notification would be a message about new software, or a change to AvaTax that may

        affect you, or a potential issue with your company''s tax profile.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

        * This API is available by invitation only. To request access to this feature, please speak to a business development manager and request access to [NotificationsAPI:Create].'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 123
                accountId: 202011901
                companyId: 34345
                referenceObject: Company Return
                referenceId: 692
                severityLevelId: Neutral
                category: Certificate Expiration
                message: The certificate of your company is nearing its expiration, please consider renewing it.
                needsAction: true
                actionName: Certificate Renewal
                actionLink: www.xyz.com
                dismissed: false
                expireDate: '2023-08-13T00:00:00+00:00'
                createdUserId: 442323
                createdDate: '2018-05-05T00:00:00'
                modifiedUserId: 442323
                modifiedDate: '2018-05-07T00:00:00'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiV2NotificationsById
      x-operation-id-source: derived
  /api/v2/notifications:
    post:
      tags:
      - Registrar
      summary: Avalara CreateNotifications
      description: 'This API is available by invitation only.


        Create a single notification.


        A notification is a message from Avalara that may have relevance to your business. You may want

        to regularly review notifications and then dismiss them when you are certain that you have addressed

        any relevant concerns raised by this notification.


        A Global notification is a message which is directed to all the accounts and is set to expire within

        a certain time and cannot be dismissed by the user. Make accountId and companyId null to create a global notification.


        An example of a notification would be a message about new software, or a change to AvaTax that may

        affect you, or a potential issue with your company''s tax profile.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

        * This API is available by invitation only. To request access to this feature, please speak to a business development manager and request access to [NotificationsAPI:Create].'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 123
                accountId: 202011901
                companyId: 34345
                referenceObject: Company Return
                referenceId: 692
                severityLevelId: Neutral
                category: Certificate Expiration
                message: The certificate of your company is nearing its expiration, please consider renewing it.
                needsAction: true
                actionName: Certificate Renewal
                actionLink: www.xyz.com
                dismissed: false
                expireDate: '2023-08-13T00:00:00+00:00'
                createdUserId: 442323
                createdDate: '2018-05-05T00:00:00'
                modifiedUserId: 442323
                modifiedDate: '2018-05-07T00:00:00'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2Notifications
      x-operation-id-source: derived
  /api/v2/accounts/{accountId}/subscriptions:
    post:
      tags:
      - Registrar
      summary: Avalara CreateSubscriptions
      description: 'This API is for use by Avalara Registrar administrative users only.


        Create one or more new subscription objects attached to this account.

        A ''subscription'' indicates a licensed subscription to a named Avalara service.

        To request or remove subscriptions, please contact Avalara sales or your customer account manager.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 12345
                accountId: 123456789
                subscriptionTypeId: 2
                subscriptionDescription: AvaTaxPro
                effectiveDate: '2015-01-01'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: accountId
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2AccountsByAccountIdSubscriptions
      x-operation-id-source: derived
  /api/v2/accounts/{accountId}/subscriptions/{id}:
    delete:
      tags:
      - Registrar
      summary: Avalara DeleteSubscription
      description: '# For Registrar Use Only

        This API is for use by Avalara Registrar administrative users only.


        Mark the existing account identified by this URL as deleted.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: accountId
        in: path
        schema:
          type: string
        required: true
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2AccountsByAccountIdSubscriptionsById
      x-operation-id-source: derived
    put:
      tags:
      - Registrar
      summary: Avalara UpdateSubscription
      description: '# For Registrar Use Only

        This API is for use by Avalara Registrar administrative users only.


        Replace the existing subscription object at this URL with an updated object.

        A ''subscription'' indicates a licensed subscription to a named Avalara service.

        To request or remove subscriptions, please contact Avalara sales or your customer account manager.

        All data from the existing object will be replaced with data in the object you PUT.

        To set a field''s value to null, you may either set its value to null or omit that field from the object you post.


        ### Security Policies


        * This API requires one of the following user roles: BatchServiceAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 12345
                accountId: 123456789
                subscriptionTypeId: 2
                subscriptionDescription: AvaTaxPro
                effectiveDate: '2015-01-01'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: accountId
        in: path
        schema:
          type: string
        required: true
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiV2AccountsByAccountIdSubscriptionsById
      x-operation-id-source: derived
  /api/v2/servicetypes/servicetypes:
    get:
      tags:
      - Registrar
      summary: Avalara ListServiceTypes
      description: 'For Registrar Use Only

        This API is for use by Avalara Registrar administrative users only.


        Returns the full list of Avalara-supported subscription types.

        This API is intended to be useful for identifying which features you have added to your account.

        You may always contact Avalara''s sales department for information on available products or services.

        You cannot change your subscriptions/service directly through the API.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2ServicetypesServicetypes
      x-operation-id-source: derived
  /api/v2/passwords/{userId}/reset:
    post:
      tags:
      - Registrar
      summary: Avalara ResetPassword
      description: '# For Registrar Use Only

        This API is for use by Avalara Registrar administrative users only.


        Allows a system admin to reset the password for a specific user via the API.

        This API is only available for Avalara Registrar Admins, and can be used to reset the password of any

        user based on internal Avalara business processes.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPTester, FirmAdmin, FirmUser, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

        * This API is available to Avalara system-level (registrar-level) users only.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                newPassword: NewPassword789~~!
                suppressResetPasswordEmail: false
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: userId
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2PasswordsByUserIdReset
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
